### ISSUE TITLE
InstaPy' object has no attribute 'aborting'

### ISSUE THREAD

**Issue by vsuhov** [Nemixalone/GUI-tool-for-InstaPy-script#13]
For some reason i can not start the script. 
Here is the log 

Traceback (most recent call last): File "quickstart.py", line 3, in <module> session = InstaPy(username='stoxies', password='pass') File "C:\Python27\InstaPy\instapy\instapy.py", line 40, in __init__ self.set_selenium_local_session() File "C:\Python27\InstaPy\instapy\instapy.py", line 79, in set_selenium_local_session if self.aborting: AttributeError: 'InstaPy' object has no attribute 'aborting'

**Comment by Nemixalone** [comment]
First please **delete** username and password when posting here you don't want to get your acc stolen.

Second try updating InstaPy files and the GUI.
